---
version: 2.1
jobs:

  test:
    parameters:
      pg-version:
        type: string
      stack-yaml:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: make sure dockerfile is built
          command: cd orville-postgresql-libpq && docker-compose build -q
      - run:
          name: run tests against << parameters.stack-yaml >>
          command: cd orville-postgresql-libpq && PG_VERSION=<< parameters.pg-version >> docker-compose run --rm dev stack --stack-yaml << parameters.stack-yaml >> test --ghc-options=-j --flag orville-postgresql-libpq:ci

  formatting-check:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          keys:
            # Note that format-repo.sh is where we have the version of fourmolu set
            - tooling-lint-v1-{{ checksum "orville-postgresql-libpq/scripts/format-repo.sh" }}
      - run:
          name: make sure dockerfile is built
          command: cd orville-postgresql-libpq && docker-compose -f docker-compose.ci-lint.yml build -q
      - run:
          name: run formatting so we can see if there is a diff
          command: cd orville-postgresql-libpq && docker-compose -f docker-compose.ci-lint.yml run --rm lint sh -c ./scripts/format-repo.sh && sudo chown -R circleci:circleci .stack-root
      - save_cache:
          paths:
            - orville-postgresql-libpq/.stack-root
          # Note that format-repo.sh is where we have the version of fourmolu set
          key: tooling-lint-v1-{{ checksum "orville-postgresql-libpq/scripts/format-repo.sh" }}
      - run:
          name: check for formatting diff
          command: cd orville-postgresql-libpq && sh -c scripts/format-check-ci.sh

workflows:
  version: 2.0
  test:
    jobs:
      - test:
          matrix:
            parameters:
              pg-version: ["pg11", "pg12", "pg13", "pg14", "pg15"]
              stack-yaml: ["stack-nightly-2022-11-01.yml", "stack.yml", "stack-lts-18.9.yml", "stack-lts-18.7.yml", "stack-lts-17.3.yml", "stack-lts-17.0.yml", "stack-lts-16.12.yml"]

      - formatting-check
